#!/bin/bash

docker stop nginx-proxy 2>/dev/null
docker rm nginx-proxy 2>/dev/null

docker run -d \
  --name nginx-proxy \
  -v /docker/nginx/config/ssl/:/etc/nginx/certs:rw \
  -v /etc/nginx/vhost.d \
  -v /usr/share/nginx/html \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  -p 80:80 \
  -p 443:443 \
  jwilder/nginx-proxy

docker stop nginx-proxy-companion 2>/dev/null
docker rm nginx-proxy-companion 2>/dev/null

docker run -d \
    --name nginx-proxy-companion \
    -v /docker/nginx/config/ssl/:/etc/nginx/certs:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --volumes-from nginx-proxy \
    jrcs/letsencrypt-nginx-proxy-companion
