#!/bin/bash

# Change this to where you want to save our certs
CERTS_PATH="/docker/nginx/config/ssl/"

docker run -d \
  --name nginx-proxy \
  -v $CERTS_PATH:/etc/nginx/certs:rw \
  -v /etc/nginx/vhost.d \
  -v /usr/share/nginx/html \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  -p 80:80 \
  -p 443:443 \
  jwilder/nginx-proxy

docker run -d \
    --name nginx-proxy-companion \
    -v $CERTS_PATH:/etc/nginx/certs:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --volumes-from nginx-proxy \
    jrcs/letsencrypt-nginx-proxy-companion
